### ISSUE TITLE
Demo fails to run on Mac OS X

### ISSUE THREAD

**Issue by BradNeuberg** [belltailjp/selective_search_py#10]
I've compiled according to the instructions given in the README. However, when I attempt to run the demo:

./demo_showhierarchy.py ~/Downloads/wald-wicker-04-1000.jpg --k 500 --feature color texture --color rgb

I get the following error:

Traceback (most recent call last):
  File "./demo_showhierarchy.py", line 43, in <module>
    (R, F, L) = selective_search.hierarchical_segmentation(img, args.k, mask)
  File "/usr/local/selective_search_py/selective_search.py", line 65, in hierarchical_segmentation
    F0, n_region = segment.segment_label(I, 0.8, k, 100)
AttributeError: 'module' object has no attribute 'segment_label'

I'm able to 'import segment' if I open a Python shell, but it seems like it can't resolve the 'segment_label' symbol. Mac OS X 10.10.5.

**Comment by BradNeuberg** [comment]
This had to do with Python3 boost issues on my end; closing.

**Comment by dgolden1** [comment]
@BradNeuberg I'm having the same issue. Can you describe your fix?
