### ISSUE TITLE
import segment undefined symbol:_ZN5boost5numpy5emptyEiPKlRKNS0_5dtypeE

### ISSUE THREAD

**Issue by nhfmaster** [belltailjp/selective_search_py#15]
When running ./demo_showcandidates.py image.jpg, I got a problem.

Traceback (most recent call last):
  File "./demo_showcandidates.py", line 12, in <module>
    import selective_search
  File "/home/nhfmaster/git/selective_search_py/selective_search.py", line 10, in <module>
    import segment
ImportError: /home/nhfmaster/git/selective_search_py/segment.so: undefined symbol: _ZN5boost5numpy5emptyEiPKlRKNS0_5dtypeE

Why did it happen? While compiling the C++ program, I've added needed libs.(only use make can't build successfully) Following is my build order:

g++ -fPIC -c -o segment.o segment_py.cpp -I/home/anaconda2/include/python2.7 -I/home/git/selective_search_py/segment -I/usr/local/boost/lib -lpython2.7 -lboost_python

Hope you can help me!!!

**Comment by nhfmaster** [comment]
It was solved. So just forget it.

**Comment by Patrickctyyx** [comment]
@nhfmaster Could you please tell me how do you solve this problem? Thanks a lot!

**Comment by Hun-ger** [comment]
> It was solved. So just forget it.

Could you please tell me how do you solve this problem? Thanks a lot!

**Comment by tltsilveira** [comment]
Anyone solved this problem?
