### ISSUE TITLE
make ERROR <pyconfig.h>

### ISSUE THREAD

**Issue by sdadia** [belltailjp/selective_search_py#17]
When I run  : make 
it gives me an error 
/usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                                    ^

It says there is no file/directory

**Comment by aelnouby** [comment]
Export the /include/python directory 
I fixed it with this export:
`export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python3.5m/"`

Reference:
http://stackoverflow.com/questions/19810940/ubuntu-linking-boost-python-fatal-error-pyconfig-cannot-be-found

**Comment by Adityakunwar** [comment]
Where shall I include the export line? I tried it in my .bashrc file but it didn't work

**Comment by imsamiksha** [comment]
> Where shall I include the export line? I tried it in my .bashrc file but it didn't work

Same with me
