### ISSUE TITLE
undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE

### ISSUE THREAD

**Issue by northeastsquare** [belltailjp/selective_search_py#2]
Hello , I meet this problem 
selective_search_py/segment.so: undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE. 
Could you give me some hints? And by the way,How fast this project produce regsion proposals for one image? Could it be fast enough to  be used to produce region proposals for realtime video process?
Thank you.

**Comment by belltailjp** [comment]
Hi, sorry for the late.
Give me further contextual information about the error you got.
- Environment (OS, version of gcc, python, boost)
- How did you build the segmentation library
- It seems an execution error. Which line in the python code does it occur?
- ...
