### ISSUE TITLE
ImportError when running the demo

### ISSUE THREAD

**Issue by Hun-ger** [belltailjp/selective_search_py#34]
segment.so: undefined symbol: _ZN5boost5numpy6detail13get_int_dtypeILi8ELb1EEENS0_5dtypeEv
platform linux -- Python 3.6.7, pytest-4.4.0, py-1.8.0, pluggy-0.9.0

**Comment by Hun-ger** [comment]
the CMakeLists.txt has changed

**Comment by santoshreddy254** [comment]
Did you solve the issue I am facing the same issue @Hun-ger

**Comment by Hun-ger** [comment]
> Did you solve the issue I am facing the same issue @Hun-ger

try this : https://github.com/BradNeuberg/selective_search_py
